"""Preparation and authority boundaries; generated bytes here are metadata fixtures."""

from dataclasses import replace
import contextlib
import copy
import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock

from tools import bootstrap_toolchain as seed
from tools import bootstrap_stage_release as release


ROOT = Path(__file__).resolve().parents[1]


class StageReleaseTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="cupid-stage-release-test-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.linux = seed.verify_seed_inputs(ROOT / "bootstrap/seeds/i386-linux/manifest.json")
        self.windows = seed.verify_seed_inputs(ROOT / "bootstrap/seeds/i386-windows/manifest.json")
        self.snapshot, self.linux_plan, self.windows_plan = release._capture_pair(
            ROOT, self.linux, self.windows, False, True)
        self.digest = seed._source_snapshot_sha256(self.snapshot)
        self.revision = "c05c287ef2baa65750b107ade0fa146ba23d5d63"
        self.preparations = {}
        self.stages = {}
        for format_name in ("elf32", "pe32"):
            workspace = self.root / format_name
            workspace.mkdir()
            source = seed.freeze_source_inputs(ROOT, self.linux_plan, workspace / "source",
                windows_utf8=True, windows_user_link_aliases=True)
            plan = self.linux_plan if format_name == "elf32" else self.windows_plan
            object_roles = {row["name"] for row in plan["sources"]}
            object_roles.update({"start"} if format_name == "elf32" else
                                {row["name"] for row in plan["assembly_sources"]})
            stages = []
            for name in release.STAGES:
                directory = source.root / name
                directory.mkdir()
                objects = {role: directory / (role + ".o") for role in object_roles}
                tools = {role: directory / (role + (".exe" if format_name == "pe32" else ""))
                         for role in release.ROLES}
                for role, path in (*objects.items(), *tools.items()):
                    path.write_bytes((format_name + ":" + role).encode("ascii"))
                stages.append(seed.Stage(objects, tools))
            output = self.root / (format_name + "-prepared")
            release.publish_preparation(source, ROOT, self.linux_plan, self.windows_plan,
                self.linux, self.windows if format_name == "pe32" else None,
                stages, workspace, output, format_name)
            self.preparations[format_name] = output
            record = json.loads((output / "stage-preparation.json").read_bytes())
            self.stages[format_name] = tuple(seed.Stage(
                {role: output / name / row["file"] for role, row in record["stages"][name]["objects"].items()},
                {role: output / name / row["file"] for role, row in record["stages"][name]["tools"].items()})
                for name in release.STAGES)

    def context(self, **changes):
        arguments = dict(root=ROOT, linux_preparation=self.preparations["elf32"],
                         windows_preparation=self.preparations["pe32"], linux_seed=self.linux,
                         windows_seed=self.windows, source_revision=self.revision,
                         snapshot_sha256=self.digest)
        arguments.update(changes)
        return release.paired_context(**arguments)

    def request(self):
        identity, cohorts = self.context()
        path = self.root / "reviewed-release.json"
        payload = release._encode(identity)
        path.write_bytes(payload)
        return release.ReleaseRequest(path, payload, self.revision, self.digest,
                                      self.linux, self.windows, cohorts)

    def test_preparations_are_complete_and_cannot_be_bootstrap_publications(self):
        identity, cohorts = self.context()
        self.assertEqual(len(identity["artifacts"]), 12)
        self.assertEqual(identity["source_snapshot_sha256"], self.digest)
        self.assertEqual(identity["parent_linux_manifest_sha256"], self.linux.manifest_sha256)
        self.assertEqual(identity["parent_windows_manifest_sha256"], self.windows.manifest_sha256)
        for root in self.preparations.values():
            self.assertFalse((root / "bootstrap-report.json").exists())
            self.assertFalse((root / "behavior").exists())
            with self.assertRaisesRegex(seed.BootstrapError, "incomplete"):
                seed.publish_bootstrap_outputs(root, self.root / "completed")
        self.assertFalse((self.root / "completed").exists())

    def test_caller_digest_and_parent_selection_are_mandatory(self):
        with self.assertRaisesRegex(seed.BootstrapError, "caller-selected digest"):
            self.context(snapshot_sha256="0" * 64)
        with self.assertRaisesRegex(seed.BootstrapError, "caller source revision"):
            self.context(source_revision="not-a-revision")
        changed = copy.deepcopy(self.windows.manifest)
        changed["provenance"]["plan_seed_manifest_sha256"] = "0" * 64
        with self.assertRaises(seed.BootstrapError):
            self.context(windows_seed=replace(self.windows, manifest=changed))

    def test_preparation_claims_and_actual_artifact_drift_are_rejected(self):
        root = self.preparations["pe32"]
        path = root / "stage-preparation.json"
        original = path.read_bytes()
        document = json.loads(original)
        for field, value in (("status", "pass"), ("source_snapshot_sha256", "0" * 64),
                             ("parents", {}), ("format", "elf32"), ("linux_plan", {})):
            with self.subTest(field=field):
                changed = copy.deepcopy(document)
                changed[field] = value
                path.write_bytes(release._encode(changed))
                with self.assertRaisesRegex(seed.BootstrapError, "caller-owned source, plan or parents"):
                    self.context()
                path.write_bytes(original)
        artifact = self.stages["pe32"][2].tools["cupidbuild"]
        artifact.write_bytes(b"altered actual tool bytes")
        with self.assertRaisesRegex(seed.BootstrapError, "artifact bytes differ"):
            self.context()

    def test_preparation_cannot_hide_objects_or_different_fixed_point(self):
        root = self.preparations["elf32"]
        path = root / "stage-preparation.json"
        document = json.loads(path.read_bytes())
        original = copy.deepcopy(document)
        document["stages"]["stage-three"]["objects"].pop("start")
        path.write_bytes(release._encode(document))
        with self.assertRaisesRegex(seed.BootstrapError, "role inventory"):
            self.context()
        document = original
        artifact = self.stages["elf32"][2].tools["cupidc"]
        artifact.write_bytes(b"coherently different generation")
        document["stages"]["stage-four"]["tools"]["cupidc"].update(release._identity(artifact.read_bytes()))
        path.write_bytes(release._encode(document))
        with self.assertRaisesRegex(seed.BootstrapError, "stage three differs"):
            self.context()

    def test_release_accepts_semantic_order_and_rejects_every_context_change(self):
        identity, _ = self.context()
        semantic = copy.deepcopy(identity)
        semantic["artifacts"].reverse()
        release._check_record(release._encode(semantic), identity)
        for field in identity.keys() - {"artifacts"}:
            with self.subTest(field=field):
                changed = copy.deepcopy(identity)
                changed[field] = 1 if field == "source_input_count" else "changed"
                with self.assertRaises(seed.BootstrapError):
                    release._check_record(release._encode(changed), identity)
        for mutation in ("digest", "duplicate", "bool"):
            changed = copy.deepcopy(identity)
            if mutation == "digest":
                changed["artifacts"][0]["sha256"] = "0" * 64
            elif mutation == "duplicate":
                changed["artifacts"][1] = changed["artifacts"][0]
            else:
                changed["artifacts"][0]["size"] = True
            with self.subTest(mutation=mutation), self.assertRaises(seed.BootstrapError):
                release._check_record(release._encode(changed), identity)
        with self.assertRaisesRegex(seed.BootstrapError, "duplicate"):
            release._check_record(b'{"schema":"a","schema":"b"}', identity)

    def test_qualification_matches_actual_rebuild_and_materializes_owned_context(self):
        request = self.request()
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        for format_name in ("elf32", "pe32"):
            with self.subTest(format=format_name):
                stages = self.stages[format_name]
                authority = request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
                    self.linux, self.windows if format_name == "pe32" else None,
                    stages[1], stages[2], format_name)
                parent = self.linux if format_name == "elf32" else self.windows
                manifest = seed._materialize_behavior_seed(replace(parent, behavior_release=authority),
                    self.root, format_name + "-behavior", stages[2])
                provenance = json.loads(manifest.read_bytes())["provenance"]
                self.assertEqual(provenance["source_revision"], self.revision)
                self.assertEqual(provenance["source_snapshot_sha256"], self.digest)
                self.assertEqual((manifest.parent / "seed-release.json").read_bytes(), request.payload)
        request.path.write_bytes(request.payload + b" ")
        with self.assertRaisesRegex(seed.BootstrapError, "changed during qualification"):
            request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
                self.linux, None, *self.stages["elf32"][1:], "elf32")

    def test_rebuilt_cohort_cannot_differ_even_with_matching_release(self):
        request = self.request()
        self.stages["elf32"][2].tools["cupidobj"].write_bytes(b"different rebuild")
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        with self.assertRaisesRegex(seed.BootstrapError, "tools differ from prepared"):
            request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
                self.linux, None, *self.stages["elf32"][1:], "elf32")

    def test_linux_behavior_materialization_uses_authorized_candidate_plan(self):
        request = self.request()
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        for format_name in ("elf32", "pe32"):
            stages = self.stages[format_name]
            authority = request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
                self.linux, self.windows if format_name == "pe32" else None,
                stages[1], stages[2], format_name)
            parent = self.linux if format_name == "elf32" else self.windows
            path = seed._materialize_behavior_seed(replace(parent, behavior_release=authority),
                self.root, format_name + "-plan-regression", stages[2])
            document = json.loads(path.read_bytes())
            if format_name == "elf32":
                self.assertEqual(document["build_plan_sha256"], seed._build_plan_sha256(self.linux_plan))
                self.assertEqual(document["build_plan"], self.linux_plan)
            else:
                self.assertNotIn("build_plan", document)
                self.assertNotIn("build_plan_sha256", document)
            self.assertEqual(document["provenance"]["source_revision"], self.revision)
            self.assertEqual((path.parent / "seed-release.json").read_bytes(), request.payload)
            self.assertEqual(parent.live_manifest_path.read_bytes(), parent.manifest_bytes)

    def test_matching_rebuild_generations_cannot_change_prepared_objects(self):
        request = self.request()
        for stage in self.stages["elf32"][1:]:
            stage.objects["start"].write_bytes(b"same changed object in both generations")
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        with self.assertRaisesRegex(seed.BootstrapError, "objects differ from prepared"):
            request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
                self.linux, None, *self.stages["elf32"][1:], "elf32")

    def test_authorized_linux_plan_is_retained_as_immutable_bytes(self):
        request = self.request()
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        authority = request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
            self.linux, None, *self.stages["elf32"][1:], "elf32")
        expected = copy.deepcopy(self.linux_plan)
        self.linux_plan["links"]["cupidbuild"].pop()
        path = seed._materialize_behavior_seed(replace(self.linux, behavior_release=authority),
            self.root, "immutable-plan", self.stages["elf32"][2])
        self.assertEqual(json.loads(path.read_bytes())["build_plan"], expected)

    def test_wrong_retained_plan_fails_before_behavior_seed_publication(self):
        request = self.request()
        source = seed.SourceInputs(ROOT, self.snapshot, windows_utf8=True, windows_user_link_aliases=True)
        authority = request.authorize(source, ROOT, self.linux_plan, self.windows_plan,
            self.linux, None, *self.stages["elf32"][1:], "elf32")
        wrong_plan = copy.deepcopy(self.linux_plan)
        wrong_plan["links"]["cupidbuild"].remove("fat16_stage")
        self.assertNotEqual(wrong_plan, self.linux_plan)
        for payload in (release._encode(wrong_plan),
                        b'{"sources":[],"sources":[]}'):
            changed = replace(authority, linux_plan_bytes=payload)
            with self.assertRaises(seed.BootstrapError):
                seed._materialize_behavior_seed(replace(self.linux, behavior_release=changed),
                    self.root, "wrong-plan", self.stages["elf32"][2])
            self.assertFalse((self.root / "wrong-plan").exists())

    def test_runner_inserts_release_before_child_separator_and_checks_drift(self):
        calls = []
        payload = b"caller owned release"
        directory = self.root / "runner"
        directory.mkdir()
        path = directory / "seed-release.json"
        path.write_bytes(payload)
        class Runner:
            def run(_self, executable, arguments, timeout):
                calls.append((executable, arguments, timeout))
                return subprocess.CompletedProcess([], 0, "", "")
        runner = release.ReleasedBehaviorRunner(Runner(), payload)
        arguments = ["run", "--seed-manifest", directory / "manifest.json", "--root", directory,
                     "--tool", "cupidobj", "--", "wrap-text", "--seed-manifest", "child-owned"]
        runner.run(Path("cupidbuild"), arguments, 180)
        observed = calls[-1][1]
        self.assertEqual(observed[:3], ["run", "--seed-release", path])
        self.assertEqual(observed[observed.index("--") + 1:], arguments[arguments.index("--") + 1:])
        for command in ("compile-user", "compile-kernel", "compile-doom", "compile-production", "link-user",
                        "assemble-cupidasm-object", "assemble-bootloader", "assemble-smp-trampoline", "assemble-iso-pattern",
                        "embed-jpeg", "generate-ksyms", "flatten-kernel", "generate-profile-manifest"):
            runner.run(Path("cupidbuild"), [command, "--seed-manifest", directory / "manifest.json"], 190)
            self.assertIn("--seed-release", calls[-1][1])
        runner.run(Path("cupiddis"), ["--help"], 60)
        self.assertEqual(calls[-1][1], ["--help"])
        child_arguments = ["run", "--tool", "cupidobj", "--", "--seed-manifest", "child-only"]
        runner.run(Path("cupidbuild"), child_arguments, 60)
        self.assertEqual(calls[-1][1], child_arguments)
        for abi_arguments in (["verify-user-abi", "--root", directory],
                              ["verify-user-abi"],
                              ["verify-user-abi", "--root", directory,
                               "--seed-manifest", directory / "absent.json"]):
            with mock.patch.object(release, "_regular_bytes", side_effect=AssertionError(
                    "unseeded ABI commands must not observe or inject a release")):
                runner.run(Path("cupidbuild"), abi_arguments, 60)
            self.assertEqual(calls[-1][1], abi_arguments)
        class DriftRunner(Runner):
            def run(_self, executable, arguments, timeout):
                path.write_bytes(payload + b" ")
                return super().run(executable, arguments, timeout)
        with self.assertRaisesRegex(seed.BootstrapError, "changed during execution"):
            release.ReleasedBehaviorRunner(DriftRunner(), payload).run(Path("cupidbuild"), arguments)

    def test_author_preserves_existing_candidate(self):
        output = self.root / "existing-release.json"
        output.write_bytes(b"prior release")
        arguments = ["author", "--root", str(ROOT), "--linux-manifest", str(self.linux.live_manifest_path),
            "--windows-manifest", str(self.windows.live_manifest_path), "--output", str(output),
            "--linux-preparation", str(self.preparations["elf32"]),
            "--windows-preparation", str(self.preparations["pe32"]),
            "--source-revision", self.revision, "--source-snapshot-sha256", self.digest]
        with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit) as raised:
            release.main(arguments)
        self.assertEqual(raised.exception.code, 1)
        self.assertEqual(output.read_bytes(), b"prior release")
        output.unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(release.main(arguments), 0)
        release._check_record(output.read_bytes(), self.context()[0])

    def test_opened_capture_rejects_growth_and_never_reads_past_the_bound(self):
        path = self.root / "bounded-input"
        path.write_bytes(b"1234")
        original_read = os.read
        requests = []
        def grow(descriptor, count):
            requests.append(count)
            with path.open("ab") as stream:
                stream.write(b"56789")
            return original_read(descriptor, count)
        with mock.patch.object(os, "read", side_effect=grow), self.assertRaisesRegex(
                seed.BootstrapError, "changed during capture"):
            release._regular_bytes(path, 4)
        self.assertTrue(requests and all(count <= 5 for count in requests))

    @unittest.skipUnless(os.name == "posix", "FIFO replacement requires POSIX")
    def test_regular_leaf_replaced_by_fifo_is_rejected_without_waiting(self):
        path = self.root / "replace-input"
        path.write_bytes(b"prior")
        original_open = os.open
        def replace_fifo(candidate, flags):
            path.unlink()
            os.mkfifo(path)
            return original_open(candidate, flags)
        with mock.patch.object(os, "open", side_effect=replace_fifo), self.assertRaisesRegex(
                seed.BootstrapError, "changed kind or identity"):
            release._regular_bytes(path, 64)


if __name__ == "__main__":
    unittest.main()
