#!/usr/bin/env bash
# Fetch trust-anchor DERs and emit kernel/tls/tls_ca_bundle_data.c.
# Run from the repo root:
#   bash tools/fetch_ca_bundle.sh
# Requires: curl, openssl, xxd.

set -euo pipefail

OUT="kernel/tls/tls_ca_bundle_data.c"
TMP="$(mktemp -d)"
trap "rm -rf $TMP" EXIT

# (name, url-to-PEM)
ROOTS=(
  "ISRG_Root_X1|https://letsencrypt.org/certs/isrgrootx1.pem"
  "DigiCert_Global_Root_G2|https://www.digicert.com/CACerts/DigiCertGlobalRootG2.crt.pem"
  "GTS_Root_R1|https://i.pki.goog/r1.pem"
  "GTS_Root_R4|https://i.pki.goog/r4.pem"
)

emit_blob() {
  local name="$1" pem="$2"
  local der="$TMP/$name.der"
  openssl x509 -in "$pem" -outform DER -out "$der"
  # xxd -i emits a C array with the variable named after the input file.
  (cd "$TMP" && xxd -i "${name}.der") | sed "s/${name}_der\\b/${name}_DER/g"
}

mkdir -p "$(dirname "$OUT")"

{
  echo "/* Auto-generated by tools/fetch_ca_bundle.sh - do not edit. */"
  echo "#include \"x509_chain.h\""
  echo

  for entry in "${ROOTS[@]}"; do
    name="${entry%%|*}"
    url="${entry#*|}"
    pem="$TMP/$name.pem"
    echo "Fetching $name..." >&2
    curl -fsSL --max-time 30 "$url" -o "$pem"
    emit_blob "$name" "$pem"
    echo
  done

  echo "const ca_root_t TLS_CA_BUNDLE[] = {"
  for entry in "${ROOTS[@]}"; do
    name="${entry%%|*}"
    echo "    { \"$name\", ${name}_DER, sizeof(${name}_DER) },"
  done
  echo "};"
  echo "const uint32_t TLS_CA_BUNDLE_COUNT = sizeof(TLS_CA_BUNDLE) / sizeof(TLS_CA_BUNDLE[0]);"
} > "$OUT"

echo "Wrote $OUT" >&2
