#!/usr/bin/env bash
# Fetch Mozilla's root-CA bundle (via curl.se's mirror) and emit
# kernel/tls/tls_ca_bundle_data.c with the popular-CA subset.
#
# The kernel binary is capped at ~2 MB on disk (FAT16 starts at LBA
# 4096), so the full ~150-cert bundle does NOT fit. Instead this script
# picks roots whose human-readable name matches a curated regex of
# the most-used issuers (DigiCert, ISRG / Let's Encrypt, GTS, Sectigo,
# USERTrust, GlobalSign, Amazon, IdenTrust, Entrust, Baltimore,
# Starfield/GoDaddy, Microsoft).  That fits in roughly 80–90 KB of
# .data and covers the chains for almost every site you'll visit.
#
#   bash tools/fetch_ca_bundle_mozilla.sh                  # default
#   bash tools/fetch_ca_bundle_mozilla.sh <url>            # custom PEM URL
#
# If the kernel link fails with "exceeds reserved HDD kernel area",
# trim the regex below (or drop one of the broader CA families).
#
# Requires: curl, openssl, xxd.

set -euo pipefail

OUT="kernel/tls/tls_ca_bundle_data.c"
BUNDLE_URL="${1:-https://curl.se/ca/cacert.pem}"
TMP="$(mktemp -d)"
trap "rm -rf $TMP" EXIT

# Names of CAs to include.  Case-insensitive; matched against the
# header line preceding each PEM block in cacert.pem.
KEEP_RE='DigiCert|ISRG|Let.s Encrypt|USERTrust|Sectigo|GlobalSign|Amazon|IdenTrust|Entrust|Baltimore|Starfield|GoDaddy|Microsoft|GTS Root|Google Trust|AAA Certificate'

echo "Fetching Mozilla CA bundle from $BUNDLE_URL ..." >&2
curl -fsSL --max-time 60 "$BUNDLE_URL" -o "$TMP/cacert.pem"

echo "Splitting + filtering bundle ..." >&2
mkdir -p "$TMP/certs"
awk -v outdir="$TMP/certs" -v keep_re="$KEEP_RE" '
  function ci_match(s, re,    ls, lre) {
    ls = tolower(s); lre = tolower(re);
    return (ls ~ lre);
  }
  /-----BEGIN CERTIFICATE-----/ {
    if (ci_match(curname, keep_re)) {
      n++;
      fname = sprintf("%s/cert-%03d.pem", outdir, n);
      keep = 1;
    } else {
      keep = 0;
    }
  }
  keep { print > fname; }
  /-----END CERTIFICATE-----/ {
    if (keep) close(fname);
    keep = 0;
  }
  /^[A-Z]/ && !keep { curname = $0; }
  /^[A-Z]/ {
    if (length($0) > 5 && $0 !~ /^---|^==|^##/) curname = $0;
  }
' "$TMP/cacert.pem"

count=$(ls "$TMP/certs"/cert-*.pem 2>/dev/null | wc -l)
echo "Kept $count matching certificates" >&2
[ "$count" -gt 0 ] || { echo "No certs matched keep regex" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"

ok_count=0
ok_names=()
for pem in "$TMP/certs"/cert-*.pem; do
  idx=$(basename "$pem" .pem | sed 's/cert-//')
  name="MOZ_ROOT_$idx"
  der="$TMP/${name}.der"
  if openssl x509 -in "$pem" -outform DER -out "$der" 2>/dev/null; then
    ok_count=$((ok_count + 1))
    ok_names+=("$name")
  else
    echo "  skipping $(basename "$pem") (openssl rejected)" >&2
  fi
done

echo "Embedding $ok_count valid roots ..." >&2

{
  echo "/* Auto-generated by tools/fetch_ca_bundle_mozilla.sh - do not edit. */"
  echo "/* Source: $BUNDLE_URL */"
  echo "/* Roots: $ok_count */"
  echo "#include \"x509_chain.h\""
  echo

  for name in "${ok_names[@]}"; do
    (cd "$TMP" && xxd -i "${name}.der") | sed "s/${name}_der\\b/${name}_DER/g"
    echo
  done

  echo "const ca_root_t TLS_CA_BUNDLE[] = {"
  for name in "${ok_names[@]}"; do
    echo "    { \"$name\", ${name}_DER, sizeof(${name}_DER) },"
  done
  echo "};"
  echo "const uint32_t TLS_CA_BUNDLE_COUNT = sizeof(TLS_CA_BUNDLE) / sizeof(TLS_CA_BUNDLE[0]);"
} > "$OUT"

echo "Wrote $OUT ($ok_count roots)" >&2
