#!/usr/bin/env bash
# Extract function symbols from a kernel ELF and emit a C source file
# whose const blob (placed in section .ksyms) is parsed at runtime by
# kernel/ksyms.c.  Format:
#
#   Header (16 bytes, little-endian):
#     uint32_t magic        ('KSYM' = 0x4D59534B)
#     uint32_t count
#     uint32_t string_off   (offset of string table from blob start)
#     uint32_t total_size
#
#   Entries (count * 8):
#     uint32_t addr
#     uint32_t name_off
#
#   String table: NUL-terminated function names, packed.
#
# Usage: mksyms.sh <kernel.elf> <out.c>

set -euo pipefail

ELF=${1:?need elf path}
OUT=${2:?need output C path}

if ! [ -r "$ELF" ]; then
  echo "mksyms: cannot read $ELF" >&2
  exit 1
fi

# Function-like symbols only: t/T (text), w/W (weak text). Sort by address.
# Skip anonymous and compiler-generated junk (.LCnnn).
nm -n "$ELF" \
  | awk '$2 ~ /^[tTwW]$/ && $3 !~ /^\.L/ && $3 != "" { print $1, $3 }' \
  > "${OUT}.syms.tmp"

python3 - "$OUT" "${OUT}.syms.tmp" <<'PYEOF'
import struct, sys

out_path  = sys.argv[1]
syms_path = sys.argv[2]

syms = []
with open(syms_path) as f:
    for line in f:
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        addr_s, name = parts[0], parts[1].strip()
        if not name:
            continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        syms.append((addr, name))

# Stable sort by address; nm -n already does this but be explicit.
syms.sort(key=lambda x: x[0])

# Dedup by address (keep first occurrence).
seen = set()
uniq = []
for a, n in syms:
    if a in seen: continue
    seen.add(a)
    uniq.append((a, n))
syms = uniq

# Build string table and offsets.
strtab = b""
offsets = []
for _, name in syms:
    offsets.append(len(strtab))
    strtab += name.encode() + b"\0"

count    = len(syms)
hdr_size = 16
ent_size = 8 * count
str_off  = hdr_size + ent_size
total    = str_off + len(strtab)

blob  = struct.pack("<IIII", 0x4D59534B, count, str_off, total)
for (addr, _), nofs in zip(syms, offsets):
    blob += struct.pack("<II", addr, nofs)
blob += strtab

with open(out_path, "w") as f:
    f.write("/* Auto-generated by tools/mksyms.sh - do not edit. */\n")
    f.write("#include \"ksyms.h\"\n\n")
    f.write("const unsigned char\n")
    f.write("__attribute__((section(\".ksyms\"), used, aligned(4)))\n")
    f.write("ksym_blob[] = {\n")
    for i in range(0, len(blob), 16):
        chunk = blob[i:i+16]
        f.write("  " + " ".join("0x%02x," % b for b in chunk) + "\n")
    f.write("};\n\n")
    f.write("const unsigned int ksym_blob_size = sizeof(ksym_blob);\n")

print(f"mksyms: {count} symbols, {len(blob)} bytes -> {out_path}", file=sys.stderr)
PYEOF

rm -f "${OUT}.syms.tmp"
